services:
  postgres:
    image: postgres:16
    container_name: binder-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:Z

volumes:
  pgdata:
